### PR TITLE
Upgrade visitor-as in order to be AssemblyScript 20.8 friendly

### PR DESCRIPTION
**Pull request by adrien-zinger**
Make the lib a module to import not `commonjs` imports from the new version.

:warning:  This is a temporary step, we need to use a real tag when it's possible.

### CODE REVIEW

**Comment by AurelienFT** [comment]
I think @gregLibert is more appropriate as a reviewer. I haven't work on this part.

**Comment by gregLibert** [comment]
I don't see any clean solution here:
- Using an old version of assemblyscript is painful.
- The visitor-as proposed is not a TAG but a huge PR opened on April 27th with no comment from the repo owner => not sure if the branch will be merged one day.


I support the initiative taken by @adrien-zinger . We just need to add the warning in the README file for the follow-up.

**Comment by gregLibert** [comment]
A final note, when I run my linters (prettier eslint-config-google eslint-config-prettier eslint-plugin-prettier @typescript-eslint/eslint-plugin typescript @typescript-eslint/parser) I have 39 problems. Maybe we should start introducing a linter or at least create an issue about it :-).

**Comment by adrien-zinger** [comment]
> I don't see any clean solution here:
> 
>     * Using an old version of assemblyscript is painful.
> 
>     * The visitor-as proposed is not a TAG but a huge PR opened on April 27th with no comment from the repo owner => not sure if the branch will be merged one day.
> 
> 
> I support the initiative taken by @adrien-zinger . We just need to add the warning in the README file for the follow-up.

The latest version of `visitor-as` is not compatible with the latest version of assembly script. You can reproduce the bug as follow:

1. `npx massa-sc-create wasm`
2. `cd wasm`
3. Modify the assemblyscript version in `package.json` to the latest (or upgrade version with yarn)
4. `yarn install` (or npm if you prefer)
5. `yarn run build`

You get the following error:

```
yarn run v1.22.18
warning package.json: No license field
$ massa-sc-scripts build-sc && massa-sc-scripts build-sc src/main.ts build/main.wasm
Running asc src/smart-contract.ts --transform mscl-as-transformer --transform json-as/transform --target release --exportRuntime --binaryFile build/smart-contract.wasm...
WARNING Unknown option '--binaryFile'
FAILURE Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/adrien/Documents/repos/tmp/node_modules/assemblyscript/package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:693:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (/home/adrien/Documents/repos/tmp/node_modules/mscl-as-transformer/node_modules/visitor-as/as/index.js:18:32)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/adrien/Documents/repos/tmp/node_modules/mscl-as-transformer/node_modules/visitor-as/src/base.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/adrien/Documents/repos/tmp/node_modules/mscl-as-transformer/node_modules/visitor-as/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/adrien/Documents/repos/tmp/node_modules/mscl-as-transformer/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at Module.Me (/home/adrien/Documents/repos/tmp/node_modules/assemblyscript/cli/index.js:408:23)
Running asc src/main.ts --transform mscl-as-transformer --transform json-as/transform --target release --exportRuntime --binaryFile build/main.wasm...
WARNING Unknown option '--binaryFile'
FAILURE Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/adrien/Documents/repos/tmp/node_modules/assemblyscript/package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:693:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (/home/adrien/Documents/repos/tmp/node_modules/mscl-as-transformer/node_modules/visitor-as/as/index.js:18:32)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/adrien/Documents/repos/tmp/node_modules/mscl-as-transformer/node_modules/visitor-as/src/base.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/adrien/Documents/repos/tmp/node_modules/mscl-as-transformer/node_modules/visitor-as/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/adrien/Documents/repos/tmp/node_modules/mscl-as-transformer/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at Module.Me (/home/adrien/Documents/repos/tmp/node_modules/assemblyscript/cli/index.js:408:23)
Done in 2.82s.
yarn run build  9.16s user 0.45s system 324% cpu 2.965 total
```


Looking at the log error, we can see that it come from the transformer:

```sh
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/adrien/Documents/repos/tmp/node_modules/mscl-as-transformer/index.js:1:42)
```

After a little debug, I found the problem in the library `visitor-as`. Someone worked on that [here](https://github.com/willemneal/visitor-as/pull/35). Basically, it's compatible with any 0.20.x versions of AssemblyScript, but require us to be a module. That's what I do.

Note that merging that will not break the existent. Because all other projects are pointing to the version of the [transormer 0.0.1](https://www.npmjs.com/package/mscl-as-transformer). And fixes are going to be applied later on `massa-sc-scripts`, `massa-sc-std` and `massa-sc-template`. But this is the first thing we need to merge because everything else depends on that.

> 
>     * Using an old version of assemblyscript is painful.
> 

Yes, it's painful to not be up-to-date, I'm trying to resolve that problem. The version `0.20.9` of AssemblyScript will resolve a lot of bugs and makes the compilation faster and cleaner. I think that massa clients want to profit about it.

>     * The visitor-as proposed is not a TAG but a huge PR opened on April 27th with no comment from the repo owner => not sure if the branch will be merged one day.

I'm not pointing to a branch, so it's not a problem.

**Comment by gregLibert** [comment]
@adrien-zinger can we close this PR ?

**Comment by AurelienFT** [comment]
> @adrien-zinger can we close this PR ?

I don't think he will answer but I think we can close as we don't use this transformer anymore.

**Pull request closed without merging**
